# Configuration file location: /home/utt/.config/acme-lsp/config.toml

ProxyNetwork = "unix"
ProxyAddress = "/tmp/ns.utt.:0/acme-lsp.rpc"
AcmeNetwork = "unix"
AcmeAddress = "/tmp/ns.utt.:0/acme"
RootDirectory = "/"
HideDiagnostics = true
FormatOnPut = true
RPCTrace = false

[Servers]
	[Servers.gopls]
	Command = ["gopls", "serve", "-rpc.trace"]
	StderrFile = "gopls.stderr.log"
	LogFile = "gopls.log"

		# These settings gets passed to gopls
		[Servers.gopls.Options]
		hoverKind = "FullDocumentation"

	[Servers.ccls]
		Command = [
			"ccls",
		]
		StderrFile = "ccls.stderr.log"
		LogFile = "ccls.log"

[[FilenameHandlers]]
Pattern = '([/\\]go\.mod)|([/\\]go\.sum)|(\.go)$'
ServerKey = "gopls"

[[FilenameHandlers]]
Pattern = '(\.h)|(\.c)|(\.cpp)|(\.cc)|(\.def)$'
ServerKey = "ccls"

